### ISSUE TITLE
Quali python infrastructure refactoring

### ISSUE THREAD

**Issue by Costya-Y** [QualiSystems/cloudshell-networking-devices#48]
Design and implement new Quali python infrastructure.
requires QualiSystems/cloudshell-snmp#16
requires QualiSystems/cloudshell-networking-devices#46
requires QualiSystems/cloudshell-networking-devices#53

**Comment by Costya-Y** [comment]
requires QualiSystems/cloudshell-networking-devices#46

**Comment by Costya-Y** [comment]
- Simplify access and make better code reuse for the devices from the same vendor, that shares cli syntax

**Comment by GalcQuali** [comment]
duplicate.

**Comment by Costya-Y** [comment]
Completed and released.
